name: Test-comment-1
on:
  pull_request_review_comment:
    types: [created]
  # pull_request_review:
  #   types: ["submitted", "edited", "dismissed"]
  issue_comment:
    types: ["created", "edited", "deleted"]

jobs:
  approved:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"