name: PR Conversation Trigger

on:
  issue_comment:
    types:
      - created

jobs:
  trigger_on_pr_conversation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run on PR Conversation
        if: github.event.issue.pull_request
        run: |
          echo "PR conversation added!"
